### PR TITLE
InternetPrompt recognizer (JS) to Python

### PR DESCRIPTION
**Pull request by rvinothrajendran**
Internet protocol prompt has added

### CODE REVIEW

**Comment by rvinothrajendran** [comment]
@szul can you review

**Review by szul — APPROVED** [review]
:shipit: @arafattehsin

**Comment by arafattehsin** [comment]
Thank you once again @rvinothrajendran - would you mind updating the README please?

**Comment by rvinothrajendran** [comment]
Thanks @arafattehsin , once PR #12 will done , all the information update in README file at one shot.

**Pull request merged**
