### PR TITLE
Working PR for fixing CI/CD

### PR DESCRIPTION
**Pull request by szul**
Working to resolve pipeline issues.

### CODE REVIEW

**Comment by szul** [comment]
@rvinothrajendran @garypretty This is definitely a path issue. Trying out a few different options to resolve it. Also noticed that it's only running for the dialogs. Will look into how to handle it as a monorepo.

**Comment by garypretty** [comment]
Yeah, it is set up right now like the SDK python pipeline, which means you add the additional packages you want to pack in the pipeline config.  The. Net repo auto packs all projects. Would be good to improve on what we have for the python setup.

**Comment by rvinothrajendran** [comment]
@garypretty , @szul , The path issue has fixed (Issue in the setup.py file) and new package path has added into the azure-pipelines.yml file.  
I have done pipelines setup in my git repository and tested its working fine. 
Can you refer it here : https://github.com/rvinothrajendran/Internaltest
once everything is fine , I will create PR and push the code changes.

**Comment by szul** [comment]
@rvinothrajendran Go ahead and create a PR in this repo, the checks will run, and should verify that the path is working, then we'll be good to merge. If the checks pass and everything looks good, we can close this PR.

**Comment by rvinothrajendran** [comment]
@szul PR has submitted

**Pull request closed without merging**
