### PR TITLE
#1 Added numberwithunitprompt.py & numberwithtype_prompt.py file

### PR DESCRIPTION
**Pull request by rvinothrajendran**
#1  Converted C# Prompt:NumberWithUnitPrompt class to Python class 
#3  Converted Port numberWithType JS to Python
two files has added in the same PR #2

### CODE REVIEW

**Comment by arafattehsin** [comment]
Looks good to me. Thanks @rvinothrajendran for the PR.

**Review by arafattehsin — APPROVED** [review]

**Comment by rvinothrajendran** [comment]
@arafattehsin thanks for you to approved the PR . How to merge code change since I don't have write access

**Comment by arafattehsin** [comment]
I'll be merging it soon. Just finalizing a few things.

**Comment by szul** [comment]
I would like to see some unit tests added before merging, if at all possible, even if you just duplicated the tests from the JS library. A good package is pytest. We could then add the coverage package for code coverage when we get a pipeline set up.

**Comment by arafattehsin** [comment]
Totally agree with that!

**Review by garypretty — CHANGES_REQUESTED** [review]
Thank you very much for your contribution - our first fro the Python repo!
As this is the first we need to ensure we start our naming correctly.  Would you mind altering the folder structure to reflect that these are Bot Builder Community packages. 
e.g. change 'botbuilder-dialogs-prompts' to 'botbuilder-community-dialogs-prompts'

Thanks again!

**Review by garypretty — CHANGES_REQUESTED** [review]
It would also be great if you could add a readme for the prompts package, similar to this one in the JS repo.... https://github.com/BotBuilderCommunity/botbuilder-community-js/tree/master/libraries/botbuilder-dialog-prompts

**Comment by szul** [comment]
@garypretty I think he just followed the NodeJS packages, and all ours are "botbuilder-". I've been contemplating removing the "botbuilder-" completely from the NodeJS folder structure since it's _actually_ in a Bot Builder Community package... Would cut down on verbosity. I'm open to either.

@rvinothrajendran I would definitely suggest following Python best practices for file and variable names. I think Python developers primarily like snake case.

**Comment by rvinothrajendran** [comment]
Thanks @garypretty 

@szul sure will follow Python best practices

**Comment by garypretty** [comment]
Thanks @rvinothrajendran 

@szul I hadn't spotted it was the same as JS, so thanks for pointing that out.  I am happy to remove the botbuilder if it makes things less verbose for folder names. The one thing I want to ensure, hence this original comment, is that our packages are consistently showing botbuilder community so that we do not risk being confused with any official packages and we also maintain the connection to the project.

**Comment by szul** [comment]
@garypretty The NPM packages are scoped to “botbuildercommunity”.

**Comment by rvinothrajendran** [comment]
@arafattehsin @szul @garypretty , Kindly review the changes

**Review by szul — APPROVED** [review]
This is good. We will need to get the CI/CD squared away at some point, but I will add a bunch of issues separate of this PR to address those.

**Comment by szul** [comment]
@arafattehsin I'm good with this. You can be gatekeeper for the merge. I'll do some research into Python package structures and CI/CD and then load up the issues load so we can get the maturity on this repo up to the level of the others.

**Comment by arafattehsin** [comment]
Sure. I'll take care of this.

**Comment by arafattehsin** [comment]
For now, I have merged it with **master** as we did not want to hold this PR. However, from now on, just like our other repos, **develop** will be used as the default branch.

**Pull request merged**
