### PR TITLE
PR for fixed CI/CD #37

### PR DESCRIPTION
**Pull request by rvinothrajendran**
#37 
1. Path issue has fixed
2. botbuilder-community-middleware-activity-type package has added

### CODE REVIEW

**Comment by szul** [comment]
Re-running checks. Still seems to have died ☹️

**Comment by rvinothrajendran** [comment]
can you share the log

**Comment by szul** [comment]
@rvinothrajendran You should be able to click on 'details' in the checks to see. If not, see if @garypretty can give you access to the Azure Pipelines instance.

**Comment by garypretty** [comment]
Looks like this might be a deeper issue with the pipeline. It seems to be trying to use an agent that is unavailable.  I'll take a look.

**Comment by rvinothrajendran** [comment]
@szul : No , 401 - Uh-oh, you do not have access.

**Comment by garypretty** [comment]
@rvinothrajendran DM me your email address on Twitter and I can add you to the DevOps account.

**Comment by rvinothrajendran** [comment]
Hi , @garypretty If you get time, kindly check this PR.
Let’s plan python release 😊
Thank you

**Review by garypretty — APPROVED** [review]

**Pull request merged**
