### PR TITLE
Text Recognizer Middleware library

### PR DESCRIPTION
**Pull request by rvinothrajendran**
Added Text Recognizer Middleware library for Python
1. Phone Recognizer Middleware
2. Email Recognizer Middleware 
3. Url Recognizer Middleware 
4. Social Recognizer Middleware

### CODE REVIEW

**Comment by rvinothrajendran** [comment]
@szul can you kindly review

**Review by szul — APPROVED** [review]
@arafattehsin :shipit:

**Comment by szul** [comment]
@garypretty @arafattehsin Build is passing, but coveralls looks hung. Code looks fine to merge.

**Comment by garypretty** [comment]
@szul Thanks. I will check out coveralls.  Leave it with me to merge as I will need to update the build to automatically create the package for PyPi too

**Comment by szul** [comment]
@garypretty Anything you want me to look at with this?

**Comment by garypretty** [comment]
@szul No. Hoping to get a chance to get to this today.  I have just been doing some admin over in the .NET repo as we needed to get a  release out.  Just finishing up and then I will hop over to Python :) Been ill for last few days since getting back from States, so just re-surfacing.

**Comment by szul** [comment]
@garypretty Just checking. I have extensive Python experience; I've just been focused on the Node.JS side. Didn't want to leave you scrambling, if you needed help.

**Comment by garypretty** [comment]
@szul I may well come back to you for help :) My experience is minimal.  The biggest thing last time was for me to get my head around the packaging, which I have already forgotten everything I learned.

**Comment by rvinothrajendran** [comment]
@garypretty this time package name has set properly, hope we have to focus only on azure pipeline and pip package uploading.

**Review by garypretty — APPROVED** [review]

**Pull request merged**
